### PR TITLE
watch ngModel changes then update Switchery view

### PR DESCRIPTION
**Pull request by csbun**

### CODE REVIEW

**Comment by victorgb6** [comment]
Having the same issue, develop a solution by myself then I found a similar solution as mine on this pull request.

Please merge this request, it fixes a big problem.

**Comment by evdoks** [comment]
Thanks for the fix! using your fork right now. Any progress on merging this PR?

**Comment by aramonc** [comment]
@evdoks This repo is no longer in active development. At ServerGrove we stopped using it almost a month after developing it. Unfortunately it's not a priority and there are a few PRs that need to be tested & merged that will conflict with other PRs on here as well.  I highly recommend either using one of the forks or using the [pure CSS](https://github.com/servergrove/NgSwitchery#alternative) alternative.

**Comment by aramonc** [comment]
#28 upgraded Switchery to 0.8.1. I promise to make to some time to evaluate the different PRs that implement this & go with the best solution.

**Pull request closed without merging**
