### PR TITLE
add a watch on ngModel

### PR DESCRIPTION
**Pull request by rlamarche**
Add a watch on ngModel in order to update the switch if data is loaded asynchonously.
I know there is already 2 pull requests on this subject, but as my solution is quite different, I think it's good to have many choices :-)

### CODE REVIEW

**Comment by longmd** [comment]
Only solution of those presented that worked when attempting to load async data! Two thumbs up!

**Comment by 4lyn** [comment]
I confirm, only solution that works !

**Comment by magic890** [comment]
Yes it is working if you mean setting the first state in an async way.
But changes to the switch, does not reflects back to the ngModel from the parent scope. This is means that from the controller I'm unable to see any change performed to the model via the checkbox.
There is a way to fix this behaviour?

**Comment by rlamarche** [comment]
I think that you miss something, because for me it's working.
You need to bind the ng-model on the checkbox with the ng-switchery :

`<input ng-model="model" type="checkbox" class="js-switch" ui-switch checked />`

**Comment by magic890** [comment]
@rlamarche you are right. There were some problems with grunt live reloading. After cleaning the temporary cache folder, everything works fine.

**Pull request merged**
